[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
vouch_escrow = "5SGRD6bVjaD75nhMtnDqcjpVwqcqqsc6Z6sAGBwP3Q6W"

[programs.devnet]
vouch_escrow = "5SGRD6bVjaD75nhMtnDqcjpVwqcqqsc6Z6sAGBwP3Q6W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "id.json"

[scripts]
test = "yarn anchor test"
initialize = "npx ts-node scripts/initialize.ts"
